version: "3.7"

services:
  bot:
    build: .
    command: python -u /app/main.py >> /app/db/log/activity.log 2>&1
    privileged: true
    volumes:
      - .:/app
    container_name: bot
    restart: always
    expose:
        - 5420
        - 5421
    environment:
      LISTEN_HOST: '0.0.0.0'
      INSIDE_DOCKER: 'true'

  web:
    build: .
    command: uwsgi /app/app.ini
    privileged: true
    volumes:
      - .:/app
    container_name: web
    restart: always
    expose:
        - 5421
        - 5420
    depends_on:
      - bot
    environment:
      SEND_HOST: bot
      INSIDE_DOCKER: 'true'

  nginx:
    image: nginx
    volumes:
      - ./db:/db
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: nginx
    restart: always
    ports:
      - "5420:5420"
      - "80:80"
      - "443:443"
    depends_on:
      - web